config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  post '/thanks' => 'welcome#thanks'

  get '/landing' => 'welcome#landing'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	layout :resolve_layout



  def index
  end

  def thanks

  	@user=User.new
  	@user.name=params[:nombre]
  	@user.age = params[:edad].to_i
  	@user.mail=params[:email]
  	@user.save
  end

  def landing


  end


     private   
      def resolve_layout
       case action_name
         when "landing"
          "layout2"
         else 
          "application"
         end
      end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TallerPrueba</title>


  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>




  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/layout2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TallerPrueba</title>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Benjamin Castañeda</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= form_tag(thanks_path, method:
"post") do %>
Nombre:<br>
 <%= text_field_tag(:nombre) %><br>
 Email:<br>
 <%= email_field_tag(:email) %><br>
 Edad: <br>
  <%= number_field_tag(:edad) %><br>
 <%= submit_tag("Enviar") %>
<% end %>

app/views/welcome/thanks.html.erb
thanks.html.erb